class TestData:
    xkom_url = "https://www.x-kom.pl/"
    valid_user_email = "testowanie.strony.2023@gmail.com"
    valid_user_password = "12345678"
    product_philips = "Philips hue"
    occupied_email = "Ten adres e-mail jest już zajęty. Podaj inny adres lub odzyskaj hasło."
    main_page_title = "x-kom.pl - Sklep komputerowy"
    iphone = "iphone 14 pro"
    shopping_list_title = "Listy zakupowe - Sklep komputerowy - x-kom.pl"
    ringke_silicone = "Ringke Silicone do iPhone 14 Pro stone"
    ringke_silicone_black = "Ringke Silicone do iPhone 14 Pro Max black"
    something_went_wrong_message = "Coś poszło nie tak, spróbuj ponownie!"
    we_could_not_find_message = 'Przepraszamy, nie znaleźliśmy wyników dla frazy „@”'
    order_store_name = "Zamówienie - Sklep komputerowy - x-kom.pl"
    x_kom_bielany = "x-kom Wrocław Bielany"
    recipent_name = "Noname Test"
    recipent_phone_number = "555333111"
    order_confirmation = "Przyjęliśmy Twoje zamówienie"
